version: "3.7"

services:

  wanda:
    image: ghcr.io/trento-project/wanda:rolling
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/postgres
      SECRET_KEY_BASE: dummyS3cr3t
      AMQP_URL: amqp://wanda:wanda@rabbitmq
      CORS_ORIGIN: http://localhost:4000
      CATALOG_PATH: /app/catalog
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 4000:4000
    command: start
    volumes:
      - ./priv/catalog/:/app/catalog:rw
